### ISSUE TITLE
include ':sample-app' ?

### ISSUE THREAD

**Issue by dsvoronin** [MarathonLabs/marathon#11]
Why it is separated and not included in multiproject build? It would be handy(if possible) to check integration in single gradle run

**Comment by Malinskiy** [comment]
Because if you include the sample-app in the project and the sample-app sync fails then you can't fix the build in IDE: you'll need to fix all the errors outside the IDE environment and reimport the project (chicken and an egg problem).
To mitigate this I've separated marathon into two parts:
- the library with gradle plugin which is published into local maven repo (just plain folder)
- the sample app that picks up this plugin from local maven repo and uses it to run the tests
