### ISSUE TITLE
Migrate to Spek2 and kotlin test

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#148]
- [ ] Migrate to Spek 2.x (guide)[https://spekframework.org/migration/]
- [ ] Replace fluent with [kotlintest](https://github.com/kotlintest/kotlintest)

**Comment by Malinskiy** [comment]
@tagantroy I actually found several issues with spek:
1. Integration with IntelliJ requires additional plugin and doesn't allow specific test (a.k.a. `it` block) execution
2. DI injection is super hard with specs since the spec is passed as a constructor parameter, so the actual instance of the is hidden from you.

Do you think it's reasonable to actually move to kotlintest without spek? Or even plain old junit?
