### ISSUE TITLE
Add support to recognise multiple instances of emulator

### ISSUE THREAD

**Issue by witchlock** [MarathonLabs/marathon#223]
When `AndroidDevice().serialNumber` returns `realSerialNumber`, it takes `serialProp` over `serialNumber` if `serialProp` exists. This causes issue that on my environment it always return the same `serialNumber` for different emulators.

`16:39:40.235 [AndroidDeviceProvider-BootWait-1 @coroutine#2] DEBUG AndroidDeviceProvider - Device EMULATOR28X0X23X0 connected channel.isFull = false. Healthy = true`
`16:39:40.235 [AndroidDeviceProvider-BootWait-3 @coroutine#4] DEBUG AndroidDeviceProvider - Device EMULATOR28X0X23X0 connected channel.isFull = false. Healthy = true`
`16:39:40.283 [AndroidDeviceProvider-BootWait-3 @coroutine#4] DEBUG AndroidDeviceProvider - Device EMULATOR28X0X23X0 booted!`
`16:39:40.283 [AndroidDeviceProvider-BootWait-1 @coroutine#2] DEBUG AndroidDeviceProvider - Device EMULATOR28X0X23X0 booted!`

Move `serialNumber.takeIf` up before `serialProp.takeIf` could resolve this issue.

**Comment by tagantroy** [comment]
Hello @witchlock. Thanks for reporting this issue. I just created a bugfix. #224

**Comment by Malinskiy** [comment]
Hey @witchlock

This behaviour is intentional. If you move the real serial (which is present all the time) you basically ignore all the other types of serial that we expect. The order was chose specifically by the level of uniqueness it provides:
1. Custom **marathon.serialno** which user is fully responsible for
2. "ro.boot.serialno" which is supposed to be unique for phones but it's not unique for Android emulators unless you start them (manually)[https://developer.android.com/studio/run/emulator-commandline]. Keep in mind that this property is propagated at boot time which means that snapshot of the emulator will have a cached value until you cold boot it.

```bash
emulator @Nexus_5X_API_23 -prop ro.serialno=123456
```
3. hostname is generally unique for android devices
4. ddms's serialno that is not even propagated properly from the boot for some stages of connection
5. random UUID. fails after a reconnect since it's not persistent

The problem of unique Android ID is over all the stack of development, so for this specific use case I'd suggest either setprop'ing our custom **marathon.serialno** property or booting the devices the official way with **-prop ro.serialno=123456**

We can't merge this change because doing so will not allow people to fallback to hostname or ro.boot.serialno and will break the existing setups.

So for your use-case I'd suggest setting up your emulators as mentioned or if you really want this behaviour to be in the runner then creating a configuration parameter that overrides the order of serial property. Keep in mind that this might introduce bugs in case where you have a device reconnect, e.g.:

1. Beginning of execution, you have device A and B
2. Both disconnect
3. For some reason (which I've seen in practice) the serials are now different, device that is reported as A is actually B and visa versa
4. The code in marathon assumes that serials are stable, i.e. they never change, so there might be bugs in the execution which will be hard to find and fix

As for a configurable order of properties I'd introduce something like an option **preferredSerialProvider** and have several options. PR's are welcome :)

**Comment by amirzarbakhsh** [comment]
> Hey @witchlock
> 
> This behaviour is intentional. If you move the real serial (which is present all the time) you basically ignore all the other types of serial that we expect. The order was chose specifically by the level of uniqueness it provides:
> 
> 1. Custom **marathon.serialno** which user is fully responsible for
> 2. "ro.boot.serialno" which is supposed to be unique for phones but it's not unique for Android emulators unless you start them (manually)[https://developer.android.com/studio/run/emulator-commandline]. Keep in mind that this property is propagated at boot time which means that snapshot of the emulator will have a cached value until you cold boot it.
> 
> ```shell
> emulator @Nexus_5X_API_23 -prop ro.serialno=123456
> ```
> 
> 3. hostname is generally unique for android devices
> 4. ddms's serialno that is not even propagated properly from the boot for some stages of connection
> 5. random UUID. fails after a reconnect since it's not persistent
> 
> The problem of unique Android ID is over all the stack of development, so for this specific use case I'd suggest either setprop'ing our custom **marathon.serialno** property or booting the devices the official way with **-prop ro.serialno=123456**
> 
> We can't merge this change because doing so will not allow people to fallback to hostname or ro.boot.serialno and will break the existing setups.
> 
> So for your use-case I'd suggest setting up your emulators as mentioned or if you really want this behaviour to be in the runner then creating a configuration parameter that overrides the order of serial property. Keep in mind that this might introduce bugs in case where you have a device reconnect, e.g.:
> 
> 1. Beginning of execution, you have device A and B
> 2. Both disconnect
> 3. For some reason (which I've seen in practice) the serials are now different, device that is reported as A is actually B and visa versa
> 4. The code in marathon assumes that serials are stable, i.e. they never change, so there might be bugs in the execution which will be hard to find and fix
> 
> As for a configurable order of properties I'd introduce something like an option **preferredSerialProvider** and have several options. PR's are welcome :)

None of the methods work to change ro.serialno in emulator

**Comment by Malinskiy** [comment]
I suggest you file a bug with whoever owns the emulator, i.e. Google's Android emulator team
