### ISSUE TITLE
Feature: Firebase test lab integration?

### ISSUE THREAD

**Issue by witchlock** [MarathonLabs/marathon#228]
Just wondering is there any plan to integrate or support vendors like Firebase test lab or AWS device farm? Or is this supposed to be extended by introducing vendors?

**Comment by Malinskiy** [comment]
Hey @witchlock 

As far as my understanding of FTL goes it's not possible at the moment because there is no support for full control over devices (we require DDMS access to Android devices and ssh access to iOS simulator). Currently the approach FTL takes is `just give us binaries, we know what to do with them`, but marathon is geared towards power users who understand the specifics of testing their app.

Theoretically it would be possible to implement this, because I doubt FTL uses something different than DDMS internally. This would require effort on the Google's side. Assuming Google stick to the same isolation from client approach marathon would need to be executed on the FTL side somewhere to gain access to the devices.

The same problem exists for all the test runners with custom logic, e.g. [Spoon](https://github.com/square/spoon/issues/513)

And keep in mind that projects that are leveraging FTL for the execution effectively are just wrappers around Google's code.

Hope that answers your question. I'd be quite excited if someone from Google's side would be able to help achieve this

**Comment by witchlock** [comment]
Thanks so much for your reply @Malinskiy, that explains a lot. I really appreciate what `marathon` has brought on to the table for mobile testing. The reason I asked is to seek potentials between `local` and `cloud`

There is a FTL only test runner called [flank](https://github.com/TestArmada/flank), they share some  concept similar to `marathon` at certain degree which has explained [here](https://medium.com/walmartlabs/flank-smart-test-runner-for-firebase-cf65e1b1eca7)

Understand the restriction now, thanks again
