### ISSUE TITLE
Flakiness strategies and Sharding strategies

### ISSUE THREAD

**Issue by tagantroy** [MarathonLabs/marathon#28]
TODO @Malinskiy

**Comment by Malinskiy** [comment]
Flakiness strategy works after the sharding one. The idea is that flakiness anticipates the flakiness of the test based on the probability of test passing and tries to maximize the probability of passing when executed multiple times. For example the probability of test A passing is 0.5 and configuration has probability of 0.8 requested, then the flakiness strategy multiplies the test A to be executed 3 times (0.5 x 0.5 x 0.5 = 0.125 is the probability of all tests failing, so with probability 0.875 > 0.8 at least one of tests will pass).

So for the flakiness we want **probability-based-strategy**

All of this happens inside one shard, so separated shards have separate multiplications.

So with sharding we need only 2 strategies: 
- the one we already have (execute tests as fast as possible)
- and we also need **N-count strategy**

For example I want to execute my tests 5 times on all of the devices in the pool. Unfortunately we can't implement the strategy execute all tests on each of all devices: this will break when some device will fail and even if we reconnect more devices then it poses strange cases like do we resume the execution of the tests from the time of failure, or do we restart the whole process again on a new device. So fixed N-count strategy is simpler and easier to implement without dealing with edge cases because people will want different things, but the idea of this mode is to check the stability of tests.

**Comment by tagantroy** [comment]
@Malinskiy How **retry strategy** integrated with this **flakiness strategy**?

**Comment by Malinskiy** [comment]
Retry strategy works after the sharding and flakiness (which are both before the actual execution). Retry is a realtime strategy that takes effect after the execution of tests or failure of some device.

In case of failure of a test run it should check the shard if there are already retries present. If there are enough retries scheduled by flakiness strategy then it is basically NoOp. If all prescheduled retries failed then it should add more in case user configured it so. For example user specified up to 3 retries. Flakiness added 2. Then if all failed - retry strategy adds one more to the execution shard.

**Comment by tagantroy** [comment]
#32
