### ISSUE TITLE
How to execute tests against only 1 shard of X shards?

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#353]
How can I have marathon split up tests in a deterministic way? For example, let’s say a module has 100 tests, I want to split them into 4 different shards, and run tests against one of those shards (so only 25 of the tests)?

previously I did this with Spoon using `--numShards 4 --shard-index 0`

**Comment by Malinskiy** [comment]
Hey @ZakTaccardi

If you want to split the tests into deterministic groups then I suggest marking them with an annotation (something like `@Group1`,`@Group2`) or separating them by package. Then you can use `filteringConfiguration`. Otherwise, you can just specify the FQDN's of the classes.

What's your use-case for this?

**Comment by ZakTaccardi** [comment]
we have the unfortunate limitation of being able to only spin up one emulator per jenkins instance

so to work around this we shard the tests into X groups, and run a separate jenkins job for each group.

Our current workflow with Spoon is:

```
// jenkins job 1
./gradlew lib:spoonDebugAndroidTest -PspoonNumShards=4 -PspoonShardIndex=0
// jenkins job 2
./gradlew lib:spoonDebugAndroidTest -PspoonNumShards=4 -PspoonShardIndex=1
```
And basically spoon just divides the tests automatically for us.

And if we need a 3rd job, we just increase the shard count
```
// jenkins job 1
./gradlew lib:spoonDebugAndroidTest -PspoonNumShards=3 -PspoonShardIndex=0
// jenkins job 2
./gradlew lib:spoonDebugAndroidTest -PspoonNumShards=3 -PspoonShardIndex=1
// jenkins job 3
./gradlew lib:spoonDebugAndroidTest -PspoonNumShards=3 -PspoonShardIndex=2
```

And this guarantees that all tests in `:lib` are executed

Note, we are using https://github.com/jaredsburrows/gradle-spoon-plugin

**Comment by ZakTaccardi** [comment]
> If you want to split the tests into deterministic groups then I suggest marking them with an annotation (something like @Group1,@Group2) or separating them by package. 

This won't work for us because it would require us to modify our code under test

> you can just specify the FQDN's of the classes.

This may work with additional manual effort, but I don't think we would have the ability to get the FQDN's of all the classes at the time we need to inform 

I believe that the `AndroidJUnitRunner` itself supports test sharding via:

https://developer.android.com/training/testing/junit-runner#sharding-tests

But I think marathon would need to support this as well? As this is an Android thing specifically, I imagine that maybe it could be a part of the vendor implementation? (sorry, new to Marathon)

**Comment by Malinskiy** [comment]
Marathon's approach is to construct batches of tests dynamically. Sharding (as in spoon sharding or junit runner sharding) is a very bad idea. Shard are created at the beginning of the test execution. You can't rebalance the execution of tests ~~if~~ when a device failure occurs or you're dealing with flakiness coming from tests.
Shards are also prone to device-dependence: a test can pass on one device (possibly due to side effects) but not on the other one. Having a shard associated with a device will only exaggerate this problem.

Please read through the docs and understand how marathon addresses the problems of flakiness. 

It would also help us if you explain what you actually want to achieve with this.

**Comment by rupinr** [comment]
> we have the unfortunate limitation of being able to only spin up one emulator per jenkins instance

Hey @ZakTaccardi , You can use the following to create multiple emulator instances, It uses docker containers for emulators.  It is still in the early testing phase. But it may suit you.

https://github.com/rupinr/andromeda

**Comment by Malinskiy** [comment]
@ZakTaccardi marathon is not a platform, it's just a test runner. vendor-android assumes that devices are available via adb server. If you have the resources to spin up emulators I suggest creating a basic version of mobile farm and connect the devices using `adb connect` TCP/IP. 

Spinning up emulators locally on the agent doesn't scale since you can't have a huge agent to spawn 50+ emulators. And this is exactly the scenario that marathon is targeted: having 50 or even hundreds of devices that in parallel execute your tests.

I've built android-farm in my previous company for the purpose of infinite horizontal scaling. Take a look if you're interested in this topic. https://github.com/agoda-com/android-farm

The approach with shards might work for small/medium setups but cannot be scaled properly. The reason behind is you'd need to setup 50+ jobs in CI. Each of them might fail and these runs are not connected and do not share devices between each other. Compare that with a pool of devices for a single run in marathon: even if a device will fail, the test run still continues since we have devices to spare. Reporting is also significantly simplified: you get 1 report rather than 50. Also, there is a problem with test runs being unbalanced: it is impossible to separate the shard in such a way that all the test runs finish at the same point of time. If they don't finish at the same time then you'd be wasting resources of the finished test runs.

**Comment by ZakTaccardi** [comment]
yeah I completely agree that it's far better to set up an emulator farm. It would just be nice if Marathon supported test sharding like I described to allow us to drop support for Spoon and get our foot in the door with Marathon before we eventually go through the effort to set up an emulator farm

**Comment by tagantroy** [comment]
Hey @ZakTaccardi. I implemented sharding as a temporary solution for my previous company. It is very simple to implement. 
Basically you have steps described below:
1. Parse APK and extract list of tests
2. Process this list of tests and generate multiple marathon configs(It may use some analytics to make shards balanced by time for example). You can use filters in marathon config.
3. Clone these configs to different gitlab/jenkins runner and execute it

**Comment by ZakTaccardi** [comment]
> Parse APK and extract list of tests

This isn't known at the time of gradle invocation, so it isn't really doable. Unless the filters can somehow receive the APK as input, which I doubt

**Comment by Malinskiy** [comment]
You can extract the list of test same way we're doing in marathon: https://github.com/linkedin/dex-test-parser. If you don't want to develop a separate tool for that, it's possible to reuse your gradle build code and create a task that outputs the test methods

**Comment by ZakTaccardi** [comment]
> it's possible to reuse your gradle build code and create a task that outputs the test methods

So I would need to figure out the test APK that marathon would use, parse it for tests, and then whitelist those tests and methods.

Which means I need to:
1. create a gradle task whose output is a list of test methods
2. use the output of that task as input to the `MarathonExtension`

I think the `MarathonExtension` would need to leverage the [Gradle Property API](https://docs.gradle.org/current/userguide/lazy_configuration.html#working_with_task_dependencies_in_lazy_properties) as  input for me to achieve this?

Ultimately the goal is to be able to achieve an API like:

```
./gradlew lib:marathonDebugAndroidTest -PmarathonNumShards=4 -PmarathonShardIndex=0
```

**Comment by ishammoho** [comment]
I have a similar use case, where I was to split my test suite in to 3 groups and run on 3 emulators parallel e.g. 120 tests, 1-40 tests in Emu 1, 41 - 40 in Emu 2 and 81 to 120 in Emu 3 (we are doing this to get faster build times especially in our PR builds). We are using composer at the moment which identifies attached emulators automatically and shard accordingly. Just wondering whether it's possible to get similar outcome using marathon. I have tried it using marathon with no luck. Thanks in advance for your help.

**Comment by ishammoho** [comment]
Hey @ZakTaccardi , Just wondering whether you were able to get sharding working(sharding similar to spoon) using marathon.

**Comment by ZakTaccardi** [comment]
@ishammoho I was not - we are still using Spoon over Marathon for this reason. We don't have the ability to use an emulator farm yet, so we require this feature so we can deterministically retry a specific shard that failed. More specifically:

We need to run 100 tests:

* shard 1, executes 50 tests, all pass
* shard 2, executes 50 tests, a test fails

We need to be able to re-execute the second 50 tests again
