### ISSUE TITLE
Is it possible to run the tests only on the given Android emulators with the given config file?  

### ISSUE THREAD

**Issue by sparepal** [MarathonLabs/marathon#387]
Out of 
Devices attached:
Emulator 5554
Emulator 5556

I want to run Marathonfile1 on emulator-5554
And I want to run Marathonfile2 on emulator 5556

Is this possible?

**Comment by QAutomatron** [comment]
You can try two `Marathonfile ` with different `includeSerialRegexes ` and `excludeSerialRegexes`.

**Comment by sparepal** [comment]
Can you give me an example of how to use this option?

**Comment by sparepal** [comment]
Was able to pass the serial numbers to the 
IncludeSerialRegex: [5554,5556] 
To trigger only on these

**Comment by sparepal** [comment]
The Mac terminal comes to a hang when two instances of marathon have started at the same time(with different include serial regexes).

How do I run two marathon test runs concurrently?

**Comment by Malinskiy** [comment]
Hi @sparepal 

Yes, it's possible as mentioned above by @QAutomatron. If you ever need to run two instances of marathon concurrently with different configurations you need to:
1. Specify different includeSerialRegex/excludeSerialRegex, e.g:
```yaml
includeSerialRegexes: ["emulator-5554"]
```
and
```yaml
includeSerialRegexes: ["emulator-5556"]
```

2. Specify different `outputDir`, otherwise, you'll be overwriting your results in real-time
3. Run two instances with two different Marathonfiles, e.g. `marathon -m Marathonfile_filter1` and `marathon -m Marathonfile_filter2`

Observe that you'll see the device filtering happen in the log:
```
D 13:23:30.696 [main @coroutine#47] <Scheduler> device emulator-5554 associated with poolId omni
D 13:23:30.743 [main @coroutine#47] <Scheduler> device emulator-5556 is filtered out by configuration. skipping
```

Keep in mind that running concurrently in gradle is not supported, only in CLI.

Closing the issue, if you have additional questions - feel free to reopen.
