### ISSUE TITLE
[Android] Named Parameterized tests will stay uncomplete

### ISSUE THREAD

**Issue by mikepenz** [MarathonLabs/marathon#393]
**Describe the bug**

When you have tests in a project with parameterized and give them a name, marathon will fail to detect their results and mark them as uncompleted

**To Reproduce**

Change the `ParameterizedTest.kt` to have this as params: `@Parameterized.Parameters(name = "compute test for input {0}: {1}")`

**Expected behavior**

The tests run and succeed

**Logs and reports**

Happens all the time for named parameterized builds

**Devices (please complete the following information):**
 - Device: Any Android device
 - OS: Any Android version

**Additional context**

I have had a look to see if I can open a PR but I failed to see where the best start would have been. Also I was struggling to see if there was a good way to debug things like this?

**Comment by Malinskiy** [comment]
@mikepenz Development workflow I use is just opening marathon in IntelliJ and using the default Run Configurations that we share using git. There is one for android-app for example and you can just use the _Debug_ button for starting in debug mode.

In order to fix this issue, we would have to significantly change the parser though: right now it's just a dex binary parser, but the for parameterized tests the only stable way is to actually execute the tests on device with [log](https://github.com/Malinskiy/adam/blob/master/src/main/kotlin/com/malinskiy/adam/request/testrunner/InstrumentOptions.kt#L45) option, collect the output and parse it into a list of tests.

**Comment by mikepenz** [comment]
@Malinskiy thank you so much for your answer. and the explanation. 

Sounds like this would be significant. :/ not sure if it would benefit other areas?

**Comment by Malinskiy** [comment]
I don't know of any other area where this functionality is needed

**Comment by trevjonez** [comment]
given that the test orchestrator already has a similar invocation into AJUR to enumerate the test list, perhaps that mechanism could be used and skip trying to replicate the test enumeration from dex all together?

**Comment by Malinskiy** [comment]
@trevjonez android junit runner is executed on the device itself. marathon requires the list of all tests to be available prior to the execution. the only way how you would reuse this is to use a device and that's basically what is suggested in the https://github.com/Malinskiy/marathon/issues/393#issuecomment-656030245 with the [log](https://github.com/Malinskiy/adam/blob/master/src/main/kotlin/com/malinskiy/adam/request/testrunner/InstrumentOptions.kt#L62)

I'd be happy to see people report the use-cases here rather than coming up with new solutions. We know what the solution is. If there is a demand for this - I/we can invest time, but I have to see that people miss this feature.

The code in AJUR is running in the same classloader AFAIU (https://github.com/android/android-test/blob/eaddf2ba037e79ac13a2e70c716773ed4c7e3cf2/runner/android_junit_runner/java/androidx/test/internal/runner/TestRequestBuilder.java#L799). We don't have that luxury in marathon.

**Comment by trevjonez** [comment]
So another issue that comes up with using dex to enumerate tests is that we end up with a single invocation for the full set of the test matrix when parameterized, which means the behavior of applicationPmClear is inconsistent. (this also means the html report is broken)

Not to say that I think marathon is handling it incorrect but it is going to mean that a stateful parameterized test is most likely going to fail on marathon when it would have passed when being ran under the androidx orchestrator. I would imagine similar inconsistencies would show up when running the tests via studio/agp which may end up being a super common source of friction with developers that habitually use studio rather than the tool in a given build/test pipeline

**Comment by Malinskiy** [comment]
Another potential issue here is that requesting the execution of named parameterized test by method fails without reporting any tests:
```
$ adb shell am instrument -w -m -e debug false -e class 'com.example.NamedParameterizedTest#test' com.example.test/androidx.test.runner.AndroidJUnitRunner
```

While the request for the class itself succeeds as expected:
```
$ adb shell am instrument -w -m -e debug false -e class 'com.example.NamedParameterizedTest' com.example.test/androidx.test.runner.AndroidJUnitRunner
```

Strangely this behaviour is only observed when using named parameters, example - https://github.com/MarathonLabs/marathon/blob/test/named-parameterized-tests/sample/android-app/app/src/androidTest/java/com/example/NamedParameterizedTest.kt#L15
