### ISSUE TITLE
Could not find allure dependecy

### ISSUE THREAD

**Issue by stMayhem** [MarathonLabs/marathon#456]
After updating the marathon plugin from version **0.5.2** to **0.6.1** when I run command `./gradlew marathon` the following problem appeared:

```
A problem occurred configuring project ':app'.
> Could not resolve all artifacts for configuration ':app:classpath'.
   > Could not find io.qameta.allure:allure-kotlin-commons:2.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/qameta/allure/allure-kotlin-commons/2.1.2/allure-kotlin-commons-2.1.2.pom
       - https://plugins.gradle.org/m2/io/qameta/allure/allure-kotlin-commons/2.1.2/allure-kotlin-commons-2.1.2.pom
     Required by:
         project :app > com.malinskiy.marathon:marathon-gradle-plugin:0.6.1 > com.malinskiy.marathon:core:0.6.1
```

This is my project level repositories dependencies:
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url = uri("https://jitpack.io") }
    }
}
buildscript {
    repositories {
        google()
        jcenter()
        maven(url = "https://maven.fabric.io/public")
    }
}

```

**Comment by Malinskiy** [comment]
This is related to https://github.com/allure-framework/allure-kotlin/issues/49 because allure-kotlin is currently uploaded only to their bintray. For now please add the new repo to setting.gradle `https://dl.bintray.com/qameta/maven`, but hopefully soon the issue will be resolved and it's going to be available via mavenCentral which would not require any additional repos

**Comment by stMayhem** [comment]
Thank you! Problem solved

**Comment by smugleafdev** [comment]
Currently ```https://dl.bintray.com/qameta/maven``` gives a "Forbidden!" result and [your allure issue #49](https://github.com/allure-framework/allure-kotlin/issues/49) seems to have missed the March deadline. Is there a solution for those of us having this issue, besides downgrading?

**Comment by Malinskiy** [comment]
@smugleafdev the only solution I can think of is to have a maven proxy setup (Nexus/Artifactory) that proxies `https://dl.bintray.com/qameta/maven` so that while the upstream is down - you still can pull from the proxy, but it should've been set up before this issue happened. Right now it won't be able to help you since the proxy also can't pull the dependencies.
