### ISSUE TITLE
Pulling /sdcard/allure-results failed with vendor ADAM

### ISSUE THREAD

**Issue by JacobKant** [MarathonLabs/marathon#471]
**With vendor ADAM allure ondevice reports pull not work**

**To Reproduce**
Steps to reproduce the behaviour:
1. create default project
2. add allure-kotlin and configure it in tests
3. add marathon config
4. copy marathon cli 0.6.1 in root project folder
5. run from root project folder ./marathon-0.6.1/bin/marathon -m ./Marathonfile

Marathonfile - 
```
name: "testProject"
outputDir: "./marathon"
fallbackToScreenshots: false
strictMode: false
testOutputTimeoutMillis: 90000
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 10
  retryPerTestQuota: 2
vendorConfiguration:
  type: "Android"
  applicationApk: "app/build/outputs/apk/debug/app-debug.apk"
  testApplicationApk: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
  autoGrantPermission: false
  serialStrategy: "automatic"
  instrumentationArgs:
    debug: "false"
  applicationPmClear: false
  testApplicationPmClear: false
  vendor: ADAM
  allureConfiguration:
    enabled: true
  screenRecordConfiguration:
    preferableRecorderType: "video"
```
    
additional information - 
1. host OS - Windows 10
2. shell for commands - git bash
3. behavior - file of allure report created in "allure-device-results" but file is empty
   
**Expected behavior**
allure report successfully pulled from device to allure-device-results folder 
(same behavior like vendor DDMLIB (with DDMLIB it work))

**Logs and reports**
log - [log.txt](https://github.com/Malinskiy/marathon/files/6156741/log.txt)

**Devices (please complete the following information):**
 - Any default android emulator, i try on Pixel XL API 27

**Comment by Malinskiy** [comment]
Hey @JacobKant. Thanks for reporting this issue.

The path to file is actually wrong `/sdcard/allure-results\c4527a28-1470-49f0-b269-5bdda6fb17a0-result.json`, there seems to be an issue with the `/` vs `\`. Also, I see that the shell execution can not pick up the exit code properly.

I never tested marathon with Windows OS and we currently don't have any tests running in this environment which is the reason why this was not picked up.

I will install windows and try to check what's wrong, but, unfortunately, I don't know of any open-source CI solution that supports running Android Emulator in a Windows environment. Without this part, Windows integration will always fail because we don't continuously test this (we currently don't have any support/funding for the project and setting up such CI would require it).

**Comment by Malinskiy** [comment]
Would you be able to test out the version in the PR #472?

**Comment by JacobKant** [comment]
Thank you, I built the cli from the last develop and now it works correctly

**Comment by Malinskiy** [comment]
Awesome news! I'll close the issue then. This fix will be part of the next release
