### ISSUE TITLE
Screenshots for failing tests is missing in the test report

### ISSUE THREAD

**Issue by pavanagarwal** [MarathonLabs/marathon#545]
**Describe the bug**
We cannot see screenshots for failing tests in the html test repot. We do see a blank screen recording and it has actual videos in the reports directory but looking for screenshots that occupy less space. Also is there a way to turn off the screen recording if we have screenshots available by some other property/flag?

**Expected behavior**
- Screenshots should be visible for failing tests
- Actual Video or Screen recording should be displayed in the report

**Devices (please complete the following information):**
 - Device: emulator
 - OS: API 26, 28, 29

**Additional context**
Running tests in CI in emulators spun via genymotion cloud

**Comment by Malinskiy** [comment]
Hey @pavanagarwal, thanks for taking the time to submit the issue.
Can you please clarify, are you observing that marathon collects both mp4 and gif at the same time?

Just an FYI, the screen recording configuration is described here - https://marathonlabs.github.io/marathon/ven/android.html#screen-recorder-configuration

The HTML report doesn't show test retries, so if the test succeeded in the end - it will contain only that recording. If you need to investigate the failures in that scenario - just browse the report folder, or alternatively generate an allure report that supports showing test retries. If the test fails then a screen recording will be present in the HTML report, provided the device is not faulty and nothing flaky happened with the screen recording process.

**Comment by pavanagarwal** [comment]
@Malinskiy : Thanks for your response. No Marathon does not collect both mp4 and gifs at the same time.

Screen recording config worked in disabling the videos as well as gifs. Thanks for pointing the config parameter for same.

Is there a link/post handy on generating allure report? I do see allure-results folder reports/marathon path.

I'm still trying to figure out how to fix the missing logs in local as well as CI and blank timeline in html report generated in CI.

**Comment by Malinskiy** [comment]
If you want to talk about the logs - there is a recently opened ticket #544. Docs also mention the common reason why some things are missing in the report - https://marathonlabs.github.io/marathon/doc/faq.html#my-logsscreenshots-are-missing-from-the-html-report

If there is nothing more related to the screenshots problem then please consider closing the ticket.

As for the allure report, you can use `allure generate` using the allure cli inside the marathon's report folder to generate an HTML version of the report. Or you can use other allure's means like a TeamCity plugin, that's why it's not embedded into marathon, so that you can choose how you process the report's raw data.

**Comment by pavanagarwal** [comment]
Videos/GIFs are now displayed and accessible as per the above mentioned **screen-recorder-configuration** and CSP policy change for video assets in our CI. Thanks @Malinskiy for your quick help on this. We still see an issue in missing log files in both CI and local (even after starting the http server) and I will add that in comment for open issue - https://github.com/MarathonLabs/marathon/issues/544
