### ISSUE TITLE
Sorting Tests in a Class based on its Name

### ISSUE THREAD

**Issue by dilip-tc** [MarathonLabs/marathon#546]
**Is your feature request related to a problem? Please describe.**
SortingStrategy is currently supporting success-rate and execution-time based on previous run history , so cant able to run the tests in particular order it is defined in the code

**Describe the solution you'd like**
In our case , we need to sort tests based on its name like Ascending order
And for packages need to sort Classes based on its name

**Describe alternatives you've considered**
none

**Additional context**
Previously while running test through commandLine , we would get the tests in order while using @FixMethodOrder(MethodSorters.NAME_ASCENDING)
In our class

**Comment by Malinskiy** [comment]
Hey.

Can you please explain why you need this particular feature? Does it bring any performance or stability into the test run?

Thanks

**Comment by dilip-tc** [comment]
Hey @Malinskiy,
For some apps, we have dependent test cases. Like the first test case provides the data for the second one. In such cases we need to run certain tests in order
In such cases , when the tests are performed in order we able to achieve more successful tests in a less execution time
Thanks,

**Comment by Vacxe** [comment]
@dilip-tc hey, thanks for the issue. However:

Does I got it correctly that u have depended UI tests? Because if that's true please immediately engage for refactoring.

```
...
fun test1() {...}

fun test2() {...}

fun testN() {...}
```

If u have 1000 tests in the same class and just a first one is failed it will create a horrible overhead of execution.

---

Please follow those rule:
**Each test should past independently**

@dilip-tc just please to confirm is I got your issue with a right way

**Comment by dilip-tc** [comment]
Yes @Vacxe ,
Being aware of the test dependency complications , but still using in very few conditions like in some cases avoiding test dependency make redundant steps which takes higher execution time, other than these few test cases all other test cases are independent , so if there is option to run test cases in order will help to run tests in lesser execution time  
Thanks,

**Comment by Vacxe** [comment]
@dilip-tc so, you have a kind of hack in your UI test implementation, which contradict to paradigm of testing and you wanna to have support it in test runner? 

---

What I can advice:
* **Don't create a dependent tests**
* You can create a particular test for each screen without feature flow management
* If you have 3 dependent tests, logically thats means you have only ONE what's named End-To-End or integration. You can extract those tests to different scope and run it nightly.

**Comment by Malinskiy** [comment]
@dilip-tc I definitely understand why you would want the test runner to support something like this in your particular situation. However, Marathon's key fundamental values are performance and stability. Having tests depend on each other is a sure way of reducing the stability of test execution.

I see 2 ways to solve your use case:
1. Refactor tests. Move all of your scenarios into one test. To have visibility inside this test (I assume you're doing the separation to understand where exactly did the test fail) try using [allure's steps](https://github.com/allure-framework/allure-kotlin/blob/44e4cd7b863dd280690c2fe5502b8717d9e86038/allure-kotlin-junit4/src/test/kotlin/io/qameta/allure/kotlin/junit4/samples/TestWithTimeout.kt#L9). This will give you visibility into which part of the test scenario fails
2. Fork marathon and write a custom [SortingStrategy](https://github.com/MarathonLabs/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/execution/strategy/SortingStrategy.kt). We will not be able to accept such a PR rhough because it contradicts our values.

I will advise you to pursue option 1 since this will increase stability of your tests in general regardless of the test runner that you're using.

We'll try to add an answer to this question in our documentation soon.

**Comment by dilip-tc** [comment]
Thank you for the detailed explanation @Malinskiy  and @Vacxe , Yes @Malinskiy currently using Allure's steps for the tests , will try to refactor the old tests too , Thanks
