### ISSUE TITLE
Test runner doesn't work properly when test name is 256 characters or more

### ISSUE THREAD

**Issue by tech-ganesh** [MarathonLabs/marathon#555]
**Describe the bug**
Test runner doesn't work properly when test name is 256 characters or more.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a test with test name 256 character or more
2.Execute the marathon binary.

**Expected behavior**
Test runner should run successfully. 

**Logs and reports**

**Devices (please complete the following information):**
 - Device: Any Device
 - OS: MacOS

**Additional context**

**Comment by Malinskiy** [comment]
Hey @ganesh0026, thanks for submitting the issue. Can you please define "doesn't work properly"? What specifically doesn't work for you?

**Comment by tech-ganesh** [comment]
Hi @Malinskiy, I have observed the "File too long" error. 
We have lot of tests with large test name and runner didn't progress and trying to rerun the incomplete tests.

**Comment by Malinskiy** [comment]
This is an expected behaviour: most Linux filesystems have a limit of 255 symbols for the path, windows - 260, hence the limitation that marathon checks.

Generated report file paths will be truncated and the presence of this error doesn't stop the test run. This is an issue with your code rather than marathon. Please rename your tests so that the generated files are within the limits of the OS.

If your test run doesn't finish and you think it's because of this problem - please attach the logs of the execution in debug mode

**Comment by tech-ganesh** [comment]
Yes, There is OS level limit of 256 symbols for path in MacOS.

We have observed the file path was not getting truncated with the test runner and throwing the error "File too long".
The runner was adding some extra random text at the end of file name. 

We have large number of tests ~3k hence renaming each test wont be a good option for now.

**Comment by Malinskiy** [comment]
Which version of marathon are you using?

**Comment by tech-ganesh** [comment]
marathon v0.6.4
