### ISSUE TITLE
Documentation issue gradle plugin wants "codeCoverageEnabled = true" not "isCodeCoverageEnabled = true"

### ISSUE THREAD

**Issue by simonpoole** [MarathonLabs/marathon#562]
**Describe the bug**

The documentation claims that the gradle configuration should contain isCodeCoverageEnabled = true to enable code coverage https://marathonlabs.github.io/marathon/doc/configuration.html#code-coverage this however does not work, codeCoverageEnabled = true however does.

**To Reproduce**

gradle plugin 6.5, both ddmlib and ADAM vendor variants. Seting _isCodeCoverageEnabled = true_ results in 

    Could not set unknown property 'isCodeCoverageEnabled' for extension 'marathon' of type com.malinskiy.marathon.MarathonExtension.

Setting _codeCoverageEnabled = true_  is accepted for both vendor implementations (see note at end).

**Expected behavior**

Documentation reflects what works (at least roughly :-)).

**Logs and reports**

**Additional context**

Language wise _codeCoverageEnabled_ makes more sense, so it is really just a question of fixing the documentation.

Note: the ddmlib implementation doesn't seem to actually set the instrumentation parameter and no coverage files actually get generated.

**Comment by Malinskiy** [comment]
Hey @simonpoole, thanks for submitting the issue

I double-checked the configuration code and I believe you're referring to the groovy only configuration for gradle plugin. For kts `isCodeCoverageEnabled` does work since it's a property on the extension.

Could you please confirm you're using groovy syntax?

PS: if you need to collect the code coverage you should be using adam module: work on ddmlib is only in bugfixing mode and not on introducing new features since ddmlib vendor is deprecated and will be removed.

**Comment by simonpoole** [comment]
Yes using groovy. Sorry mentioned that I wasn't using Kotlin in the other issue but forgot it here.

**Comment by simonpoole** [comment]
> PS: if you need to collect the code coverage you should be using adam module: work on ddmlib is only in bugfixing mode and not on introducing new features since ddmlib vendor is deprecated and will be removed.

The problem was because Adam requires at least gradle 6.8 (not documented, there's an issue with the Kotlin runtime with earlier versions) I started off with the ddmlib implementation and there is no hint that coverage doesn't work with it, so again a documentation issue.
