### ISSUE TITLE
Use app writeable directory for coverage files on Android 11

### ISSUE THREAD

**Issue by simonpoole** [MarathonLabs/marathon#570]
**Is your feature request related to a problem? Please describe.**
Currently generating coverage files on Android 11 and later requires requesting and granting the global MANAGE_EXTERNAL_STORAGE permission to the app under testing, as the /sdcard/coverage directory created is otherwise not accessible by the app. While this workaround can be restricted to the debug version of the app, this is naturally sub-optimal from a testing perspective as the app is running with permissions that it will not have in production and which will hide any file access related issues.

**Describe the solution you'd like**
Configure the instrumentation runner to write to a directory that is writable by the app under testing, for example /sdcard/Download/coverage.

Alternatively the coverage file destination directory could be made configurable, but IMHO that is not really worth the effort. 

**Describe alternatives you've considered**
The alternative is granting the permission, which has negative side effects as outlined above.

**Additional context**

A quick test that the suggested destination actually works can be done with (groovy gradle, MANAGE_EXTERNAL_STORAGE not requested)

```
...
    instrumentationArgs { 
        put("coverageFile", "/sdcard/Download/coverage/coverage.ec")
    }
    fileSyncConfiguration {
        pull.add(
            new com.malinskiy.marathon.android.configuration.FileSyncEntry(
                "Download/coverage",
                com.malinskiy.marathon.android.configuration.AggregationMode.DEVICE_AND_POOL
            )
        )
   }
...
````

**Comment by Malinskiy** [comment]
If you specify anything in the pull configuration - the `MANAGE_EXTERNAL_STORAGE` permission will be granted. The problem here is because most of the extensions on the test side write to specific directories that require this permission, e.g. allure-kotlin writes to /sdcard/allure-results. Also I don't see any reason why the `Download` directory will always be named this way (hello custom firmwares).

The current approach will always work for pulling any files from the external storage. While it's possible to configure everything properly with isolation, this endeavour requires effort outside of marathon first (e.g. a convention on where to place the files related to the test).
I think we can decouple the permissions granting from the pull configuration, but sadly this will already break existing users who depend on this behaviour already.

**Comment by simonpoole** [comment]
>Also I don't see any reason why the `Download` directory will always be named this way (hello custom firmwares).

The name and special handling of Download is baked fairly hard in to Android, this is probably the last thing a custom firmware would want to change, so the risk here is very low. However if that is a concern, then making the coverage directory configurable is the way to go (1).

> 
> The current approach will always work for pulling any files from the external storage. While it's possible to configure everything properly with isolation, this endeavour requires effort outside of marathon first (e.g. a convention on where to place the files related to the test). I think we can decouple the permissions granting from the pull configuration, but sadly this will already break existing users who depend on this behaviour already.

But that isn't a problem, the app only -actually- gets the permission if it has requested it, so there is no need to change the behaviour in that respect. So for example in my case I simply wouldn't configure the permission in the manifest and all is fine and dandy.

(1) note that if there was a placeholder for the current test serial number that could be used in the configuration to get an unique filename you wouldn't actually need to make the directory configurable, as my example could then be modified to save to unique files. So that would be a possible alternative solution.

**Comment by trevjonez** [comment]
What about doing a separate utility APK with an out of process service that utilized [AndroidX FileProvider API's](https://developer.android.com/reference/androidx/core/content/FileProvider) to expose files as content URI's to the test process? 

Can we even customize where the instrumentation writes the `.ec` file? Perhaps this could be overcome by adding a test run listener to the test process to push the file into the content uri from the FileProvider at the end of the invocation?

At that point the storage may as well be plain internal storage, and the adb file pull could even be replaced with the marathon APK process pushing the data back to the marathon host via `adb reverse` and something like gRPC on said reverse port?

Potentially complicated but would pull most if not all the file system complexity into a package marathon can control the implementation of in order to provide a better UX.

Such an out of process model might also allow some overhead reduction between test runs since `[test]ApplicationPmClear` wouldn't depend on pulling files to complete before running.

Additionally this could simplify the upfront marathon configuration since the Marathon APK process would be able to tell the Marathon host exactly what files were produced from a test invocation.

**Comment by simonpoole** [comment]
> Can we even customize where the instrumentation writes the `.ec` file? Perhaps this could be overcome by adding a test run listener to the test process to push the file into the content uri from the FileProvider at the end of the invocation?
> 
See my example above.
