### ISSUE TITLE
Option to not use fully qualified class names in log files

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#574]
I'm not a fan of having my logs be full of red. The new path length limit is triggering on about half of my tests though:

> <FileManager> File name length cannot exceed 176 characters and has been trimmed to ...

Rather than generating file names with \<fully qualified class name>#\<test name>-\<random string>, I'd love the option to have the fully qualified class name instead use just the class name.

**Comment by Malinskiy** [comment]
The underlying problem is the file path limit of the OS. With the addition of test retries we needed to add uuid to the test to allow us to have unique filenames for retries.
If we remove the package from filename then there is a chance that your tests will be overwriting the same file if you have same test class under a different package.
We can remove all of the test name from the files which will save some space, so the files will be just uuids and not human to readable.
Another option without any changes is to move the project folder on your machine closer to the '/' and save some path space.
The log is warning you because if there is not enough characters, all of your test files might have the same name (e.g. first character of your package without anything else).

**Comment by VictorIreri** [comment]
Does the `outputConfiguration` > `maxPath` option, introduced in https://github.com/MarathonLabs/marathon/issues/650,  solve this for you @smugleafdev?
Docs: https://marathonlabs.github.io/marathon/doc/configuration.html#max-file-path

**Comment by smugleafdev** [comment]
@VictorIreri It sure does! Thank you, I missed this.
