### ISSUE TITLE
Use Action<T> instead of Closure and T.()-> in Gradle plugin APIs

### ISSUE THREAD

**Issue by vlsi** [MarathonLabs/marathon#584]
For instance,

https://github.com/MarathonLabs/marathon/blob/afcaecff4eca59b6430d846b2c05ac0f182cdebe/marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/gradle/MarathonExtension.kt#L78-L84

should have been

```kotlin
    fun analytics(block: Action<AnalyticsConfig>) {
        block.invoke(analyticsConfiguration)
    }

    fun batchingStrategy(block: Action<BatchingStrategyConfiguration>) {
        block.invoke(batchingStrategy)
    }
```

That would work for both Kotlin and Groovy.

**Comment by Malinskiy** [comment]
Hi @vlsi, thanks for submitting the issue!
Since this is a bug, can I please ask you to be specific as to what is not working (a particular use-case maybe)? I'd like to see a behaviour that is expected and behaviour that is observed for a bug report.

Or maybe I misunderstood and this is a refactoring request to rework the current codebase using different APIs which I'd be happy to do. Just wanted to clarify the context of the issue here.

**Comment by vlsi** [comment]
I do not think it affects clients directly, however,
1) It duplicates the code (so bugs might be possible)
2)  The current calls to `analytics {...}` would invalidate, and re-create `AnalyticsConfig` objects, so it basically makes impossible to configure the options from different places (e.g. one option from one plugin and another option from another one)

```kotlin
 fun analytics(block: AnalyticsConfig.() -> Unit) { 
     analyticsConfiguration = AnalyticsConfig().also(block) 
 } 
```

3) `Closure` arguments do not provide IDEs with a clue on the expected argument type, so the "bug" is like "missing autocomplete".

**Comment by Malinskiy** [comment]
Nice, I didn't know about the IDE behaviour.
Would you consider creating a PR with the proposed changes? I'd be happy to review and accept it if you have the time.

**Comment by vlsi** [comment]
Oh, I just noticed your tweet on Gradle plugin. I've never worked with Android / iOS projects, so I'm afraid I won't have time for the PR.

**Comment by Malinskiy** [comment]
The plugin is a generic Gradle project and doesn't require any knowledge about Android or iOS, I'd be happy to assist you with the setup.
But if it's time that's the issue - that's okay as well, I'll pick the suggestion when I'll have some time for this.

**Comment by vlsi** [comment]
It is more of a time issue (which is consumed by https://github.com/apache/jmeter/pull/674), and Android/iOS was more like "I'm not sure I would be able to test it appropriately".

**Comment by Malinskiy** [comment]
@vlsi so it turns out that using Action is not straightforward here: while Kotlin correctly accepts a lambda and uses appropriate receiver type, Groovy is passing the receiver as a parameter for some reason. See https://github.com/MarathonLabs/marathon/issues/621#issuecomment-1090026601 for more info. Would appreciate your help on this.
