### ISSUE TITLE
Cannot configure retryStrategy and batchingStrategy using Gradle

### ISSUE THREAD

**Issue by floppydrive6** [MarathonLabs/marathon#621]
**Describe the bug**
I am trying to override default `retryStrategy` and `batchingStrategy` using Gradle plugin with:
```
marathon {
    retryStrategy {
        fixedQuota {
            retryPerTestQuota = 3
            totalAllowedRetryQuota = 30
        }
    }
    batchingStrategy {
        fixedSize {
            size = 10
        }
    }
}
```
but running task `./gradlew app:marathonContractBackendDebug` fails with:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not set unknown property 'retryPerTestQuota' for object of type com.malinskiy.marathon.gradle.RetryStrategyConfiguration.

```

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to override `retryStrategy` and `batchingStrategy` using Gradle plugin

**Expected behavior**
We should be able to override those values according to readme.

**This bug is introduced in 0.7.1 release**

**Comment by Malinskiy** [comment]
Hey @floppydrive6
The only change that might affect this is https://github.com/MarathonLabs/marathon/pull/586. I’m not sure why this doesn’t work out-of-the-box though: the Action class is supposed to be compatible with both Kotlin/Groovy version of the build script.
Could you please confirm if you’re using kts or plain Groovy scripts?
Thanks!

**Comment by floppydrive6** [comment]
Hello!
Yeah, I found the same commit which might affect this 😕 . And I am using plain Groovy scripts (`build.gradle`).

**Comment by Malinskiy** [comment]
Investigating. FYI: explicitly defining action works:
```
fixedQuota(new Action<FixedQuotaRetryStrategyConfiguration>() {
    public void execute(FixedQuotaRetryStrategyConfiguration config) {
        config.totalAllowedRetryQuota = 100
        config.retryPerTestQuota = 3
    }
})
```

Update: for some reason the configuration is passed as a parameter:
```
retryStrategy {
    fixedQuota {
        it.totalAllowedRetryQuota = 300
    }
}
```

The plugin code is defining this as follows:
```
fun fixedQuota(action: Action<FixedQuotaRetryStrategyConfiguration>) {
    fixedQuota = FixedQuotaRetryStrategyConfiguration().also { action.execute(it) }
}
```

**Comment by floppydrive6** [comment]
nice, thanks for answer @Malinskiy !
So looks like readme should be updated for those two, and passing other properties like: `timeoutConfiguration` via Gradle plugin stayed unchanged?
Or there will be 0.7.2 version with fix for this and all parameters will be passed in the same way?

**Comment by Malinskiy** [comment]
I'm trying to figure out if this can be fixed. Will report back as soon as I know if this can be fixed. If not - will revert to the old closure signature

**Comment by floppydrive6** [comment]
great, thanks a lot!

**Comment by vlsi** [comment]
@Malinskiy , I would try the following:

a) Use `Action<in ..>` for the types (the interface is declared in Java, so it lacks the type variance, and the corresponding )
B) Instantiate objects via Gradle's ObejctFactory

**Comment by Malinskiy** [comment]
So it turns out it's not possible to use a unified interface for the plugin's configuration for both Kotlin and Groovy: Kotlin uses the `@HasImplicitReceiver` annotation which is picked up by the SAM conversion plugin for kotlin compiler. This code is transformed into a lambda with actual receiver in kotlin while grovvy will always transform the lambda into a lambda with a parameter. Here is an example in the official Java plugin as a reference: https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginConvention.java#L128 where you can clearly see that it's fine to have two of the signatures around for kts/groovy. I'll introduce the helpers for the Groovy back as a result of this investigation.

**Comment by vlsi** [comment]
@Malinskiy , I believe the core of the issue is that you use `new ...` approach for instantiating objects.

For instance, `Action<..>` methods for `MarathonExtension` works out-of-the-box since you instantiate the extension via Gradle's API: `project.extensions.create("marathon", MarathonExtension::class.java)`. That is why `MarathonExtension` gets automatic Gradle treatment, and that is why there's no need to have `Closure` methods there.

However, for "subfields" you use lazy pattern with `new` instantiation, and that is why `Action` alone does not work there.

---

For instance, if you replace https://github.com/MarathonLabs/marathon-gradle-plugin/blob/213d73d0a8249b1aa4be1829b64297e1b3fca902/marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/gradle/MarathonExtension.kt#L427

as follows, then you no longer need `Closure` methods in `RetryStrategyConfiguration`:

```kotlin
open class MarathonExtension @Inject constructor(
    private val objectFactory: ObjectFactory,
) {
...
    fun retryStrategy(action: Action<RetryStrategyConfiguration>) {
        retryStrategy = objectFactory.newInstance<RetryStrategyConfiguration>().also { action.execute(it) }
    }
```

Note that `org.gradle.util.ConfigureUtil` will be removed is Gradle 9 (at least, it is what the latest javadoc mentions), so I would suggest dropping `Closure`-based method, and use `objectFactory` to instantiate the objects.
