### ISSUE TITLE
log files and report files names

### ISSUE THREAD

**Issue by stanroy** [MarathonLabs/marathon#689]
Is it possible to change names of log files and html test files? Those files are generated with names that start with ".", which makes them hidden on my system. For this reason I can't view logs even when serving content on local server. After removing the first character in those names and changing the file references in html files everything works.

So for example, after marathon finishes I have .Test-Feature#Cucumber-init-test.log and .Test-Feature.Cucumber-init-test.html. I have to remove the first character of those files, as well as adjust all the references to those files.

**Comment by Malinskiy** [comment]
First of all, this is an issue with cucumber tests specifically: the test file name is created roughly by doing `$package.$classs#method`. Cucumber tests do not report any package. I can remove the leading dot from the file name, but it would be awesome if the cucumber integration reported at least some package there: `am instrument` doesn’t expect the package to be empty anyways. This is likely to be just a missing parameter in `Description`. Can you please file a bug in https://github.com/cucumber/cucumber-android? I will do the workaround only if maintainers of cucumber-android will not be responsive

**Comment by lsuski** [comment]
Hi, I'm cucumber-android maintainer.
Regarding this issue: 
which `package` do you mean in `$package.$class#method`. In `Description` class I see that class name is used for name. The class name of course contains java package however it can also be class without any package. Could you point out which property of `Description` class should be filled. If the issue is about java class package missing in the reported name then IMHO Marathon should not expect that every class contains package in its name.

**Comment by Malinskiy** [comment]
Hi @lsuski 

The issue is that all `$package`s coming out of cucumber are empty. From a perspective of native Android tests it's technically possible to place all the codebase into the root package, but it's rarely something anyone does. The expectation here is that the `String` class name you pass to the description is a fully qualified one, i.e. includes the package. I'm not familiar with cucumber, but I expect you to organize your tests via some form of scope which can be translated to java's organisation with packages, simple class names and a method.

If that's not possible it's fine, I can do a workaround for this particular issue, but I just can't imagine seeing a report with 1000+ tests under the same package. It would be a nightmare to navigate.

Marathon supports any FQTN even the one with an empty package. The report file name though when properly formatted using Fully Qualified Test Name starts with a dot, i.e. `.X#y`, which is a hidden file.

**Comment by lsuski** [comment]
In cucumber you have features and scenarios. In `Description` class name is a feature name which is something human readable. Method name is a scenario name which is also human readable. Features can be organized in folders. There is no requirement to have each class in package and there is no requirement to have each feature in some subfolder. Even if you have such structure there is a chance that some of classes/feature files are in top level package/folder. 

E.g you have feature:
```
Feature: Guess the word

  Scenario: Maker starts a game
```

then cucumber will report `Guess the word#Maker starts a game`.

Both default AGP  gradle task `connectedAndroidTest` and Spoon do not have any issue with that. I can consider adding some setting which would set a feature relative path instead of it's title in `Description` class. This would improve readability of the report. However IMHO Marathon should still handle no package case as this is completely valid case, even from Java perspective.

**Comment by lsuski** [comment]
If Marathon supports empty package name then why file name starts with `.`?

**Comment by Malinskiy** [comment]
Spoon and native gradle tasks have abysmal support for reports around tests. Sorry for trying to make it better for the end user

Technically everything works as in the tests are executed and the reports are generated. I will implement a workaround for file naming by using some hardcoded value for the package if it is empty, but in my opinion the structure of the tests should contain more than one package

**Comment by trevjonez** [comment]
> some hardcoded value for the package if it is empty

do file systems support emoji? it would be pretty fun to have the :cucumber: as the package name for this.

**Comment by lsuski** [comment]
I'm not sure why any hardcoded value should be used. No package means no package and everything is in the same folder so this redundant dot should be removed. Nevertheless you can use testNamespace or testApplicationId. From my side I will add an option to use file name with relative path so it will look like:
`features.domain.my_feature#Some scenario`

**Comment by Malinskiy** [comment]
For consumers who depend on parsing file names into meaningful `pkg.class#method` removing a `.` in the front will potentially break parsing (`class` -> `package`, and then class not found).

What you're proposing sounds good to me and will solve all of the original issues here.
