### ISSUE TITLE
Scaling and performance

### ISSUE THREAD

**Issue by manfe513** [MarathonLabs/marathon#794]
Hi,can you please give us some advice on how to use marathon more effectively?

Our setup:
1. dedicated server with 72 cpu cores + 256Gb RAM, holds up to 72 emulators in docker containers(2 cpu core, 2048ram, 512 vm.heap)
2. teamcity runs a task: 
- command line step runs within a docker container which has marathon v8 and open-stf client built-in
- we make open-stf connect and work with adb to remove and install our app on every emulator

In total, we have ~300 ui tests running within 11.5minutes
We tried 45 emulators with 4 cpu.cores and 4096ram - but the result is the same = 11minutes
We think it's because of context switching operations at the server CPU.

Maybe we can somehow improve our scheme/configs?Any help highly appreciated, thank you!

**Comment by Malinskiy** [comment]
Hey Andrew,

There is a lot of information needed to answer this. What's the actual runtime of the tests? From your 45 parallels run it's around 9 hours, but there are a lot of parameters to consider here. From the looks of it you don't yet measure the overhead of running tests in parallel hence the confusion with trying to figure why the time is the same.

I think it's best to have a call rather than a GitHub issue. Can you contact me via [email](mailto:am@marathonlabs.io)?

**Comment by manfe513** [comment]
oh, yeah, it'll be great to have a call if you have some time
I'll accept meeting
