### ISSUE TITLE
[Android] Improve debuggability upon test hang

### ISSUE THREAD

**Issue by tabletenniser** [MarathonLabs/marathon#844]
**Describe the solution you'd like**
When a test hang, the current behavior we see for Marathon is:
* Mark all tests in the same batch as failed with a stack trace saying `Test got stuck. You can increase the timeout in settings if it's too strict` as shown in the screenshot below:
![Screenshot 2023-09-21 at 1 37 18 PM](https://github.com/MarathonLabs/marathon/assets/4755223/cb4bef19-c75a-43e1-aa45-ee5aabbc20c8)
* No client side logging is created under `marathon/log/omni/127.0.0.1-5037-emulator-5554/`

This makes it difficult to: pinpoint why all the 54 tests fail (because one test case hang and timed out, causing the other tests not run) and debug why the particular test case hang because there's no client side test log or stack trace to look at.

I would hope Marathon can:
1. Have a way to continue running the rest of tests when one test case times out.
2. Store stack trace for all active threads when test hang like this.

**Comment by Malinskiy** [comment]
Hi,

> Have a way to continue running the rest of tests when one test case times out.

when any of the test times out, it is assigned incomplete status and retried if there is a budget to do that. I suspect that you have 0 [budget set up for incomplete tests](https://docs.marathonlabs.io/intro/configure#uncompleted-test-retry-quota). After the budget is exhausted, any incomplete becomes a failure.

Another factor that contributes here is the batch size. You have one test failing a whole batch of tests, this is side effects unless there is misconfiguration on the timeouts (seems like the test takes 1 minute, is the test batch timeout setup correctly?). To minimize the effect, you can [reduce the batch size](https://docs.marathonlabs.io/configuration/batching#fixed-size-batching) or [remove batching altogether](https://docs.marathonlabs.io/configuration/batching#isolate-batching).

> Store stack trace for all active threads when test hang like this

What do you mean by active threads? Tests are running on remote devices and marathon has 0 understanding of threads on your devices. Also the code in marathon can share threads since it's all coroutine based and hence stacktraces for those coroutines are likely to give you 0 understanding into what's happening unless they're augmented by coroutine debug module which is expensive to run in production and is for debug purposes only.

I suspect you want some artifacts that are stored for failing test batch, if that's the case then video is retried for a failing test batch:
https://github.com/MarathonLabs/marathon/blob/develop/vendor/vendor-android/src/main/kotlin/com/malinskiy/marathon/android/executor/listeners/video/ScreenRecorderTestBatchListener.kt#L137
For logs if there is anything that has not been written to log files for particular tests it is written for into the test batch log file:
https://github.com/MarathonLabs/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/execution/listener/LogListener.kt#L44

I'm not sure it helps, but I don't really see what marathon can enhance here. The 1 minutes timeout sounds like a misconfiguration not just on the test budget but also on the timeout for test batch.

**Comment by tabletenniser** [comment]
Thanks for the quick response!
* We do have `uncompletedTestRetryQuota` set to 2 today. But when the test case hangs, it still hang upon retry. So I think what happens here is we run the same batch 3 times, and every time, the `NotificationSettingBottomSheetTest.whenShown_thenShowsTitle` test case hangs, causing the entire batch to be incomplete and thus fail at the end. I'm wondering if it's possible to do batching for the first attempt, and upon uncompleted tests, we then run each test case in its own batch. This way, we get both the runtime performance together with the stability
* We currently have `screenRecordConfiguration` disabled because we never realized that could be useful and we assume disabling it will make our tests run faster. I guess we can try enable it to get more debug info for scenarios like this. On that note, how does Marathon decide when to take screenshots and when to take screen recording videos?
* I uploaded the entire Marathon folder as a .zip file to https://drive.google.com/file/d/1ugKCVsgAhTpr0MEJmtuS9f9UOlQWVc53/view?usp=sharing . Any pointer on where I can find this `test batch log file`?

**Comment by Malinskiy** [comment]
@tabletenniser I glanced over the execution of this run as well as the configuration:

The test in question ran 3 times, each with 1 minute timeout.

![Screenshot_20230922_201958](https://github.com/MarathonLabs/marathon/assets/2089114/6af03199-33d2-44bf-8024-f8248d9f170f).

The configuration is questionable:
```
testBatchTimeoutMillis: 1800000
testOutputTimeoutMillis: 60000
```
This expects that a single test doesn't take more than 60 seconds, the default value is 5 minutes. This makes the batch fail even if the whole batch timeout is longer since these timeouts work individually.

The super questionable bit here is:
```
FixedSizeBatchingStrategyConfiguration(size=5000, durationMillis=600000, percentile=80.0, timeLimit=2023-09-21T14:35:08.965764Z, lastMileLength=10) 
```

You're essentially asking to run all tests in a single batch. If one of your tests times out then the test run can't recover since the limits are very strict. Suggested size for batches is in dozens and duration in several minutes. This will reduce the 'bus-factor' of your test run.

> how does Marathon decide when to take screenshots and when to take screen recording videos?

Marathon will check the presence of screenrecord binary, if it's found then videos willl be recorded. If not found then screenshots. You can also [force this via configuration](https://docs.marathonlabs.io/android/configure#screen-recorder-configuration)

> Any pointer on where I can find this test batch log file?
![image](https://github.com/MarathonLabs/marathon/assets/2089114/423464c5-2a21-4c69-8af6-c3a44b18a878)


Looking at the last test before the incomplete one:
```
09-21 15:36:35.919 9226-10520/? V/DuoLog: --> POST https://xxxxxxxxxxxxx.com/2017-06-30/password-reset?fields=
09-21 15:36:35.919 9226-10520/? V/DuoLog: Content-Type: application/json
09-21 15:36:35.919 9226-10520/? V/DuoLog: Content-Length: 33
09-21 15:36:35.919 9226-10520/? V/DuoLog: User-Agent: Duodroid/5.123.0d Dalvik/2.1.0 (Linux; U; Android 11; Android SDK built for x86 Build/RSR1.210210.001.A1)
09-21 15:36:35.919 9226-10520/? V/DuoLog: Accept: application/json
09-21 15:36:35.919 9226-10520/? V/DuoLog: [ 09-
09-21 15:36:35.919 9226-10520/? V/DuoLog: 21 15:36:35.919  9226:10520 V/DuoLog   ]
09-21 15:36:35.919 9226-10520/? V/DuoLog: {"email":"invalid_email_address"}
09-21 15:36:35.919 9226-10520/? V/DuoLog: --> END POST (33-byte body)
09-21 15:36:35.921 9226-10520/? V/DuoLog: <-- HTTP FAILED: java.lang.RuntimeException: This test is running in replay mode, but no snapshot was found. It must first be run in record mode by setting the xxxx.tools.snapshot_mode property to record.
09-21 15:36:35.923 9226-10520/? E/Volley: [417] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: This test is running in replay mode, but no snapshot was found. It must first be run in record mode by setting the xxx.tools.snapshot_mode property to record.
09-21 15:36:35.923 9226-10520/? E/Volley: java.lang.RuntimeException: This test is running in replay mode, but no snapshot was found. It must first be run in record mode by setting the xxx.tools.snapshot_mode property to record.
09-21 15:36:35.923 9226-10520/? E/Volley: 	at xxx.test.espresso.network.SnapshotInterceptor.intercept(SnapshotInterceptor.kt:43)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at xxx.networking.interceptors.TrackingInterceptor.intercept(TrackingInterceptor.kt:54)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at xxx.networking.MvvmAuthUserInterceptor.intercept(MvvmAuthUserInterceptor.kt:27)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at xxx.networking.interceptors.ExtraHeadersInterceptor.intercept(ExtraHeadersInterceptor.kt:13)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at xxx.networking.interceptors.ServiceMapHeaderInterceptor.intercept(ServiceMapHeaderInterceptor.kt:31)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at xxx.networking.interceptors.RequestTracingHeaderInterceptor.intercept(RequestTracingHeaderInterceptor.kt:46)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at xxx.networking.interceptors.UrlTransformingInterceptor.intercept(UrlTransformingInterceptor.kt:14)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at xxx.networking.OkHttpStack.executeRequest(OkHttpStack.kt:53)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:104)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
09-21 15:36:35.923 9226-10520/? E/Volley: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```
I suspect your network mocking doesn't recover and fails to do anything after that. I don't see anything, though in the logs for batches. This is from the last test before this failure `xxx.signuplogin.ForgotPasswordFlowEndToEndTest#requestEmailForNonExistentAccount-03ffe838-1013-46ab-8415-68ce937427ad.log`. Obviously, I don't have your source code so can't help with debugging.

**Comment by tabletenniser** [comment]
Thanks for the info! That's super helpful!
* We do run all tests in one batch since we figured that will make things go the fastest.All of our test cases should take <5 seconds, so a `testOutputTimeoutMillis` of 60 seconds should be very tolerant.
* I think my feature request here is so that when one testcase times out, continue running the rest of the testcases in that match instead of marking all test cases in that batch as `uncomplete`. Is it something possible to do that in Marathon? (Ideally, in my test reports, I want to see 1 test failing instead of 54 tests failing as shown in the screenshot below)
<img width="1289" alt="Screenshot 2023-09-22 at 2 21 14 PM" src="https://github.com/MarathonLabs/marathon/assets/4755223/9834b129-9b8e-41d7-adb2-0a7d451ec843">

* Thanks for the recording links. One quick question with regard to the documentation in https://docs.marathonlabs.io/android/configure/#screen-recorder-configuration. I assume I would want `screenshotConfiguration:  enabled: true` as opposed to `enabled: false` to force screenshots? Also, in screenshots mode, how does Marathon decide when to take screenshots? Does it just take screenshots every X seconds or it can detect when the Android UI changes and take screenshots?
* Thanks for the debug log pointer and link to the log from the last testcase run. Think that's enough info for us to debug for this particular failure instance.

**Comment by Malinskiy** [comment]
> I think my feature request here is so that when one testcase times out, continue running the rest of the testcases in that match instead of marking all test cases in that batch as incomplete

This is possible. You just need to increase the budget for incomplete tests and also use batching with a smaller size. If the configuration is done properly, then you will see 1 failed test (assuming all the other ones actually pass). As suggested above, I'd start with isolated batching and then increase the batch size when you have confidence in your testing code as well as the infrastructure running those tests. As I mentioned before, I'm open to considering alternatives after you've tried to setup the test run with reasonable rerun budgets and it doesn't work for you.

> I assume I would want screenshotConfiguration:  enabled: true as opposed to enabled: false to force screenshots

to force screenshots you need to disable (`enabled: false`) video recording and enable screenshots

> Thanks for the debug log pointer and link to the log from the last testcase run. Think that's enough info for us to debug for this particular failure instance.

This is exactly the point of marathon. It can provide you with information to fix the underlying issues in tests, but it also needs some budget to rerun the tests. If your budget is 0 then any issue inside a batch cascades to lots of failures.

**Comment by tabletenniser** [comment]
By `increase budget for incomplete tests`, you mean increasing the `uncompletedTestRetryQuota` setting?  We did try with isolated batching, but I think our workflow runtime increases from current 4min to 25min, which is not acceptable for us (as shown in screenshot below).
<img width="1264" alt="Screenshot 2023-09-23 at 1 16 04 AM" src="https://github.com/MarathonLabs/marathon/assets/4755223/cca5a30d-9a10-42ac-b38e-cb3ff417f3a4">

Our current set up is to have `uncompletedTestRetryQuota` set to 3 and run everything in one batch, which has really good runtime (~4min) but it's very confusing when a test case gets stuck and all test cases run after will show up as failure. So, I'm wondering if it's possible to add a `batchingStrategy:  type: "fixed-size-for-first-time-but-isolate-upon-retry"` mode so that on a happy day, things pass fast with the fixed size batching; but on a sad day, we do isolate batching upon retry so that we can isolate exactly the test case that gets stuck.

**Comment by Malinskiy** [comment]
You can only choose 2 of the 'fast/stable/cheap'. If you need fast and stable then you might need to add more devices to your test run. Having 5+ devices will bring the testing time down to you original 5m while also being reliable.

I'm happy to review a PR with a batching strategy that takes into account the incomplete test status, but I don't see this as a default logic since it will unbalance the execution of test test queue by batching size being unpredictable: if you specify 1m batch size but suddenly start having isolated batches. I do agree it's an option to solve this problem, I'm sceptical of the side-effects this will introduce.

Some of the retries might be preventive, i.e. they will be scheduled immediately without failure assuming you're using flakinessStrategy. Depending on the presence of probability of test passing, such batching strategy could schedule all the retries isolated beforehand. I'd argue that maybe it's worth it to create a batching strategy with a certain probability of passing for the whole batch rather than wait for a failure and then isolate.

As for the timeout of the test: you can definitely timeout the test from the test itself rather than relying on marathon here, i.e. [CoroutinesTimeout](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-debug/kotlinx.coroutines.debug.junit4/-coroutines-timeout/) rule. If you do this then the batch will continue to run and execute the tests that are incomplete in your scenario.

Summary: happy to accept a PR with the implementation of `fixed-size-for-first-time-but-isolate-upon-retry` or `probability-batching`

**Comment by tabletenniser** [comment]
Ah, thanks for the great info!  To be clear, we don't have much stability issue even batching all test cases together, it's just confusing when one test case hangs causing all test cases afterwards shown as failure.

We don't have historical run info hooked up to Marathon today yet (though we are actively thinking about it), so a `probability-batching` won't quite work for us.

I think adding timeouts at the JUnit test level sounds like a great idea and probably the simplest solution for us. Will try to go down that route for now, and will re-open this if that doesn't work for us and we need to implement something `fixed-size-for-first-time-but-isolate-upon-retry` batching strategy.
